# Generated by Django 4.1.7 on 2023-02-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('ogrn', models.IntegerField(max_length=13)),
                ('inn', models.IntegerField(max_length=12)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintiff_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawHelp.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawHelp.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_id', models.CharField(max_length=200)),
                ('court_case_id', models.CharField(blank=True, max_length=50)),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawHelp.defendant')),
                ('plaintiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawHelp.plaintiff')),
            ],
        ),
    ]
