# Generated by Django 4.1.7 on 2023-02-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='inn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='ogrn',
            field=models.IntegerField(),
        ),
    ]
