# Generated by Django 4.1.7 on 2023-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0002_alter_legalentity_inn_alter_legalentity_ogrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defendant',
            name='defendant_info',
        ),
        migrations.RemoveField(
            model_name='plaintiff',
            name='plaintiff_info',
        ),
        migrations.AddField(
            model_name='defendant',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='inn',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='ogrn',
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='inn',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='ogrn',
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_case_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='inner_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
    ]
