# Generated by Django 4.1.7 on 2023-02-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0003_remove_defendant_defendant_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='inn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='ogrn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='inn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='ogrn',
            field=models.IntegerField(null=True),
        ),
    ]
