# Generated by Django 4.1.7 on 2023-02-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0004_alter_defendant_inn_alter_defendant_ogrn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='inn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='ogrn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='inn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='ogrn',
            field=models.BigIntegerField(null=True),
        ),
    ]
