# Generated by Django 4.1.7 on 2023-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0005_alter_defendant_inn_alter_defendant_ogrn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_card',
            field=models.URLField(default='-'),
        ),
    ]
