# Generated by Django 4.1.7 on 2023-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0006_case_case_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
