# Generated by Django 4.1.7 on 2023-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0007_alter_defendant_id_alter_plaintiff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='inner_id',
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
