# Generated by Django 4.1.7 on 2023-02-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LawHelp', '0009_alter_case_case_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='id',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='defendant',
            old_name='id',
            new_name='defendant_id',
        ),
        migrations.RenameField(
            model_name='plaintiff',
            old_name='id',
            new_name='plaintiff_id',
        ),
    ]
